version '3.0'

# Services to run
services:
  angular: frontendApp # name of frontend service
  build: /usr/src/app # specify the directory of the Dockerfile
  ports:
    - 4200:4200
  restart: always
  
  express: backendAPI # name of backend service
  build: /usr/src/app # specify the directory of the Dockerfile
  ports:
    - 3000:3000
  links:
    - database
  restart: always

  database: mongoDB # name of BD service
  image: mongo
  ports:
    - 27017:27017
  restart: always

